### ISSUE TITLE
Ошибка 502

### ISSUE THREAD

**Issue by SPEC1AL1ST** [mispon/digiseller-express#1]
Здравствуйте, делаю всё по вашему гайду, но когда проходит оплата с уникальным кодом и на этапе проверки выдает страницу ошибки с "502 - отсутствует подходящий код оплаты". Хотя код при этом проверяется. Можно ли рассчитывать на исправление?

**Comment by mispon** [comment]
@SPEC1AL1ST Приветствую! Не думаю, что проблема в коде сервиса, скорее всего стоит проверить наличие в базе кода, подходящего под параметры платежа. Подробнее посмотреть как это происходит можно тут
https://github.com/mispon/digiseller-express/blob/master/internal/service/callback.go#L60C2-L69C3

**Comment by SPEC1AL1ST** [comment]
Так дело в том, что кода в базе нет и быть не может. Он генерируется самим Дигиселлером.
А ваш сервис используется чисто для автоматизации проверки кодов, чтобы не спрашивать об этом постоянно клиентов.

**Comment by SPEC1AL1ST** [comment]
> @SPEC1AL1ST Приветствую! Не думаю, что проблема в коде сервиса, скорее всего стоит проверить наличие в базе кода, подходящего под параметры платежа. Подробнее посмотреть как это происходит можно тут https://github.com/mispon/digiseller-express/blob/master/internal/service/callback.go#L60C2-L69C3

Так дело в том, что кода в базе нет и быть не может. Он генерируется самим Дигиселлером.
А ваш сервис используется чисто для автоматизации проверки кодов, чтобы не спрашивать об этом постоянно клиентов.
[https://clip2net.com/clip/m95389/96356-clip-61kb.png](url)

**Comment by SPEC1AL1ST** [comment]
https://c2n.me/4j56Wo1

**Comment by mispon** [comment]
Под кодом я имел в виду тот товар, который автоматически должен быть выдан клиенту после успешной оплаты. Поиск товара в бд происходит по сумме платежа, если клиент заплатил 100р, то в базе будет искаться товар стоимостью 100р, если такой товар не будет найдет, то вернется ошибка выше

**Comment by SPEC1AL1ST** [comment]
Так вон я выше скрин дал, это товар с изменяемой ценой и уникальным кодом. Вот пример
https://plati.market/itm/eve-online-isk-premium-fast-delivery/970356
Человек пишет сам количество и ему дает сумму, что нужно оплатить. После оплаты выдается уникальный код который нужно проверить. Вот код проверяется, но выдает ошибку. Хотелось бы без ошибки, а то я пока что на error.tmpl вывел успешную страницу) Если сумбурно объяснил и нужно более детально что-то - я с радостью распишу. Спасибо, заранее, надеюсь что исправите.

**Comment by mispon** [comment]
Я думаю проблема в том, что сервис предназначен не под те нужды, под которые вы хотите его использовать. Основная задача сервиса - автоматически выдать товар при покупке. Да, платеж проверяется, но это один из промежуточных шагов перед поиском товара в бд.
Поэтому никакой ошибки, которую нужно было бы исправлять здесь нет. Если вам нужна иная логика, то можно сделать форк сервиса и изменить его под свои требования

**Comment by SPEC1AL1ST** [comment]
Понял, спасибо.
